adicionado suporte a propriedade PaginaCodigo para DfePrinter
marcosgerene/Gerene.DFe.EscPos pull request #13
Opened 2024-06-07 00:13 UTC by eneiasramos

adicionado suporte a propriedade PaginaCodigo para DfePrinter

2024-06-07 16:02 UTC, marcosgerene requested changes

2024-06-07 16:02 UTC, marcosgerene commented on Gerene.DFe.EscPos/DfePrinter.cs
> +            PaginaCodigo = PaginaCodigo.pc437;
Remover esse defaul, deixar default nulo e so passar para o OpenAc de diferente de nulo.

2024-06-07 16:02 UTC, marcosgerene commented on Gerene.DFe.EscPos/DfePrinter.cs
> +            _Printer.PaginaCodigo = PaginaCodigo;
so passar para o OpenAc de diferente de nulo.

2024-06-07 16:02 UTC, marcosgerene commented on Gerene.DFe.EscPos/DfePrinter.cs
> +        public PaginaCodigo PaginaCodigo { get; set; }
Criar como nullable.

2024-06-07 16:28 UTC, eneiasramos commented on Gerene.DFe.EscPos/DfePrinter.cs
> +            PaginaCodigo = PaginaCodigo.pc437;
Feito

2024-06-07 16:28 UTC, eneiasramos commented on Gerene.DFe.EscPos/DfePrinter.cs
> +            _Printer.PaginaCodigo = PaginaCodigo;
Feito

2024-06-07 16:28 UTC, eneiasramos commented on Gerene.DFe.EscPos/DfePrinter.cs
> +        public PaginaCodigo PaginaCodigo { get; set; }
Feito

2024-06-07 23:59 UTC, marcosgerene commented on Gerene.DFe.EscPos/DfePrinter.cs
> +            if (PaginaCodigo != null)
perfeito.

2024-06-08 00:00 UTC, marcosgerene requested changes

2024-06-08 00:03 UTC, eneiasramos commented on Gerene.DFe.EscPos/DfePrinter.cs
> +        public Nullable<PaginaCodigo> PaginaCodigo { get; set; }
feito!

2024-06-08 17:12 UTC, marcosgerene approved these changes

2024-06-08 17:12 UTC, merged